management.endpoints.web.exposure.include=*
server.address=0.0.0.0
spring.jackson.property-naming-strategy=SNAKE_CASE


logging.level.org.springframework.jms=DEBUG
logging.level.org.springframework.jms.listener=TRACE
logging.level.org.apache.activemq=DEBUG


spring.config.import=classpath:user-admin-application.properties,classpath:scoring-application.properties,classpath:post-application.properties,classpath:transcodin-application.properties
