management.endpoints.web.exposure.include=*
server.address=0.0.0.0
spring.jackson.property-naming-strategy=SNAKE_CASE

spring.config.import=classpath:user-admin-application.properties,classpath:scoring-application.properties,classpath:post-application.properties,classpath:transcodin-application.properties
