spring.datasource.url=jdbc:postgresql://localhost:5432/silahub_v04
spring.datasource.username=postgres
spring.datasource.password=postgres


# Show SQL statements
spring.jpa.show-sql=true

# Format SQL nicely
spring.jpa.properties.hibernate.format_sql=true

# Show SQL with parameter values
logging.level.org.hibernate.type.descriptor.sql=TRACE


spring.config.import=classpath:post-application.properties